# Generated by Django 5.0 on 2023-12-21 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players_Attribute_Backend', '0004_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Jumping',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
