# Generated by Django 5.0 on 2023-12-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players_Attribute_Backend', '0006_alter_country_name_alter_player_club_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['Name']},
        ),
    ]
