# Generated by Django 5.0 on 2023-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players_Attribute_Backend', '0007_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Slug',
            field=models.SlugField(default='a-b'),
            preserve_default=False,
        ),
    ]
