# Generated by Django 5.0 on 2023-12-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players_Attribute_Backend', '0008_player_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Slug',
            new_name='slug',
        ),
    ]
